//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menusito.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOSITO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPOSITO()
        {
            this.COBRO = new HashSet<COBRO>();
        }
    
        public int IdDeposito { get; set; }
        public int IdUsuario { get; set; }
        public int IdCuenta { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Valor { get; set; }
        public string Proceso { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COBRO> COBRO { get; set; }
        public virtual CUENTA CUENTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
