//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menusito.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int IdPago { get; set; }
        public int IdCheque { get; set; }
        public int IdCompra { get; set; }
        public double ValorPagado { get; set; }
    
        public virtual CHEQUE CHEQUE { get; set; }
        public virtual COMPRA COMPRA { get; set; }
    }
}
