//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menusito.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCCION()
        {
            this.PRODUCCIONDETALLE = new HashSet<PRODUCCIONDETALLE>();
        }
    
        public int IdProduccion { get; set; }
        public int IdUsuario { get; set; }
        public int IdProducto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Cantidad { get; set; }
        public double Costo { get; set; }
        public string Proceso { get; set; }
        public int IdBodega { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCCIONDETALLE> PRODUCCIONDETALLE { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
